# Generated by Django 4.1.2 on 2022-11-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
